In [1]:
from scheduling_algorithm_m300 import ProductionOrderSchedulerM300
scheduler = ProductionOrderSchedulerM300()
scheduler.main_scheduling_function()

Middle point:  12
EFL sum: 1
EFL 847 sum: 4
EFL 627 sum: 0
Middle point:  12
EFL sum: 0.5
EFL 847 sum: 2.0
EFL 627 sum: 0.0
Possible windows before middle point: 19.0
Possible sashes before middle point: 0.5
[]
Starting production plan with possible types: ['R6', 'R8', 'R8S', '627', '847']
sum of scheduled orders: 1.0
sum of scheduled orders: 2.5
sum of scheduled orders: 3.5
sum of scheduled orders: 4.5
sum of scheduled orders: 10.5
sum of scheduled orders: 13.5
sum of scheduled orders: 14.0
sum of scheduled orders: 16.0
sum of scheduled orders: 19.0
sum of scheduled orders: 20.0
sum of scheduled orders: 21.5
sum of scheduled orders: 22.5
Planning finished.

In [2]:
scheduler.display_df

,goods_receiver,prd_ord_num,sap_nr,product_name,quantity,glass_type,profile_color,width,height,product,window_type,variant,is_small,is_triple,is_efl,is_urgent_till_2_pm,is_urgent_till_6_pm,is_material_available,scheduling_position,is_scheduled
7,3701/Czechy/Z,116104917,635443,R89G 054/078 H200,1.0,9G,NH,540.0,780.0,WDF,R8,HAN,True,False,False,False,False,True,1,True
10,0301/Niemcy/C,116106872,635392,R69G 054/078 H2E_,1.5,9G,NH,540.0,780.0,WDT,R6,HE_,True,False,False,False,True,True,2,True
3,0301/Niemcy/C,116097659,990800,R89G_054/098_W400,1.0,9G,WH,540.0,980.0,WDF,R8,HAN,True,False,False,False,True,True,3,True
1,0301/Niemcy/Z,116097469,635441,R69P 134/098 H200,1.0,9P,NH,1340.0,980.0,WDF,R6,HAN,True,False,False,False,False,True,4,True
0,0301/Niemcy/Z,116089969,990800,R68C_114/160_W2E_ZV,6.0,8C,WH,1140.0,1600.0,WDT,R6,HE_,False,False,False,False,False,True,5,True
9,0301/Niemcy/Z,116105907,644063,R69P 114/140 H2SF,3.0,9P,NH,1140.0,1400.0,WDT,R6,HSF,True,False,False,False,False,True,6,True
4,0301/Niemcy/Z,116097661,990815,EFL_R89PH_N_RL_09/14HAN,0.5,9P,NH,940.0,1400.0,EFL,R8,HAN,True,False,True,False,False,True,7,True
5,0301/Niemcy,116104294,251674,EFL 847 H T __ AL 06/11 G1 HAN,2.0,NaN,NaN,650.0,1180.0,EFL,847,NaN,False,False,True,False,False,False,8,True
11,0301/Niemcy/C,116107812,635520,R69G 074/118 H2E_,3.0,9G,NH,740.0,1180.0,WDT,R6,HE_,True,False,False,False,True,True,9,True
6,0301/Niemcy/Z,116104909,807249,R88C 074/140 H2SA,1.0,8C,NH,740.0,1400.0,WSA,R8S,HAN,True,False,False,False,False,False,10,True
8,0301/Niemcy/Z,116105906,644059,R69P 094/140 H2SF,1.5,9P,NH,940.0,1400.0,WDT,R6,HSF,True,False,False,False,False,True,11,True
2,0301/Niemcy/Z,116097472,791672,R88_ 105/145 H200AR,1.0,8,NH,1050.0,1450.0,WDF,R8,HAN,True,False,False,False,False,True,12,True

In [1]:
from scheduling_algorithm_m200 import ProductionOrderSchedulerM200
scheduler = ProductionOrderSchedulerM200()
scheduler.main_scheduling_function()

Middle point:  104
EFL sum: 4
Middle point:  104
Total sum of R4: 52
Total sum of R7: 98
Type to start with is R7
Type to end with is R7
First order: R79T 074/098 H100L1ZVZA
Last order: R79_ 074/118 H200
Starting production plan with possible types: ['R7']
sum of scheduled orders: 40
Window scheduled: R79T 074/098 H100L1ZVZA Quantity: 40
sum of scheduled orders: 45
Window scheduled: R75_ 074/118 H100L5 Quantity: 5
sum of scheduled orders: 57
Switch type to ['R4']
Window scheduled: R79_ 074/118 H200 Quantity: 12
sum of scheduled orders: 59
Window scheduled: R45_ 074/118 H100 Quantity: 2
sum of scheduled orders: 62
Window scheduled: EFL_R49H_N_AL_07/11HAN Quantity: 3
sum of scheduled orders: 74
Window scheduled: R49_ 074/140 H200 Quantity: 12
sum of scheduled orders: 80
Window scheduled: R48_ 065/140 H200 Quantity: 6
sum of scheduled orders: 82
Window scheduled: R45_ 065/118 H100 Quantity: 2
sum of scheduled orders: 86
Window scheduled: R49_ 054/118 H200WL Quantity: 4
sum of scheduled orders: 101
Window scheduled: R45_ 054/098 H100L5 Quantity: 15
sum of scheduled orders: 106
Window scheduled: R45_ 134/098 H100L5 Quantity: 5
sum of scheduled orders: 109
Window scheduled: R49_ 094/140 H200WL Quantity: 3
No more widths to schedule, breaking the loop.

In [2]:
scheduler.display_df

,goods_receiver,prd_ord_num,sap_nr,product_name,quantity,glass_type,profile_color,width,height,product,window_type,variant,is_small,is_triple,is_efl,is_urgent_till_2_pm,is_urgent_till_6_pm,is_material_available,scheduling_position,is_scheduled
0,1201/Francja/Z,116093419,623434,R79T 074/098 H100L1ZVZA,40,9T,NH,740,980,WDF,R7,PZ2,False,False,False,False,False,True,1,True
22,MAYDISA,116103952,503448,R75_ 074/118 H100L5,5,5,NH,740,1180,WDF,R7,EXL,False,False,False,False,False,True,2,True
23,NaN,116102660,808932,R79_ 074/118 H200,12,9,NH,740,1180,WDF,R7,HAN,False,False,False,False,False,True,3,True
3,3701/Czechy/Z,116102542,611738,R45_ 074/118 H100,2,5,NH,740,1180,WDF,R4,HAN,True,False,False,False,False,True,4,True
2,2101/Polska/C,116101734,990816,EFL_R49H_N_AL_07/11HAN,3,9,NH,740,1180,EFL,R4,HAN,False,False,True,True,False,True,5,True
4,NaN,116103083,839083,R49_ 074/140 H200,12,9,NH,740,1400,WDF,R4,HAN,False,False,False,False,False,True,6,True
5,2101/Polska/C,116099183,765628,R48_ 065/140 H200,6,8,NH,650,1400,WDF,R4,HAN,False,False,False,True,False,True,7,True
6,3701/Czechy/Z,116102541,611723,R45_ 065/118 H100,2,5,NH,650,1180,WDF,R4,HAN,True,False,False,False,False,True,8,True
13,0301/Niemcy/C,116105909,2043771,R49_ 054/118 H200WL,4,9,NH,540,1180,WDF,R4,WLS,False,False,False,False,True,True,9,True
7,MAYDISA,116103954,503767,R45_ 054/098 H100L5,15,5,NH,540,980,WDF,R4,EXL,False,False,False,False,False,True,10,True
8,MAYDISA,116104103,503781,R45_ 134/098 H100L5,5,5,NH,1340,980,WDF,R4,EXL,False,False,False,False,False,True,11,True
14,0301/Niemcy/C,116105910,2043778,R49_ 094/140 H200WL,3,9,NH,940,1400,WDF,R4,WLS,False,False,False,False,True,True,12,True
11,0301/Niemcy,116101225,839574,R39G 078/098 H2DR,12,9G,NH,780,980,WDA,R3,HAN,False,False,False,False,False,True,9999,False
10,0301/Niemcy,116101284,763017,R38_ 078/098 H1DR,6,8,NH,780,980,WDA,R3,HAN,False,False,False,False,False,True,9999,False
1,NaN,116098709,808932,R79_ 074/118 H200,12,9,NH,740,1180,WDF,R7,HAN,False,False,False,False,False,True,9999,False
9,MAYDISA,116104104,506349,R35_ 074/098 H1DR,5,5,NH,740,980,WDA,R3,HAN,False,False,False,False,False,True,9999,False
15,3301/Węgry/Z,116106766,808927,R79_ 054/098 H200,1,9,NH,540,980,WDF,R7,HAN,True,False,False,False,False,True,9999,False
12,2101/Polska/Z,116105872,893493,R39_ 074/118 H2DL,1,9,NH,740,1180,WDA,R3,HAN,True,False,False,False,False,True,9999,False
16,2101/Polska/C,116100246,990816,EFL_R79H_N_AL_09/09HAN,1,9,NH,940,980,EFL,R7,HAN,True,False,True,True,False,True,9999,False
17,2101/Polska/C,116105879,2002704,R79_ 094/098 H200,7,9,NH,940,980,WDF,R7,HAN,False,False,False,True,False,True,9999,False
19,2101/Polska,116101242,808930,R79_ 065/140 H200,6,9,NH,650,1400,WDF,R7,HAN,False,False,False,False,False,True,9999,False
18,3701/Czechy/Z,116103958,808956,R79_ 094/140 H200,1,9,NH,940,1400,WDF,R7,HAN,True,False,False,False,False,True,9999,False
21,NaN,116098711,808933,R79_ 074/140 H200,12,9,NH,740,1400,WDF,R7,HAN,False,False,False,False,False,True,9999,False
20,3701/Czechy/Z,116103956,808930,R79_ 065/140 H200,1,9,NH,650,1400,WDF,R7,HAN,True,False,False,False,False,True,9999,False

In [3]:
scheduler.production_order_numbers_for_last_positions

[116103954]